import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedEquipment() {
  // Delete existing data first
  await prisma.equipmentItem.deleteMany();
  await prisma.equipmentCategory.deleteMany();
  await prisma.equipmentBudget.deleteMany();

  const categories = [
    {
      name: "GFRC Mixing Equipment",
      slug: "gfrc-mixing",
      phase: 1,
      phaseLabel: "Phase 1 — GFRC Fabrication",
      sortOrder: 1,
      items: [
        {
          name: "Forced-Action Paddle Mixer",
          description:
            "High shear mixer critical for GFRC. Forced-action paddle design ensures proper fiber distribution and glass strand integrity.",
          why: "Standard drum mixers destroy AR glass fibers. A forced-action paddle mixer is mandatory for GFRC to achieve proper fiber distribution without damaging the strands.",
          options: JSON.stringify([
            "Imer Mortarman 120 Plus",
            "CS Unitec EMF 140",
            "Buddy Rhodes Pro Mixer",
          ]),
          costLow: 1800,
          costHigh: 3500,
          priority: "essential",
          phase: 1,
          supplierName: "Buddy Rhodes",
          supplierUrl: "https://buddyrhodes.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 1,
        },
        {
          name: "Heavy Duty Drill Mixer",
          description:
            "1/2-inch chuck high-torque drill mixer for small batches and slurry mixing.",
          why: "Needed for small test batches, slurry mixes, and situations where the paddle mixer is overkill. The 1/2-inch chuck and high torque rating handle thick cement mixes without bogging down.",
          options: JSON.stringify([
            "Makita XRH11Z with paddle",
            "DeWalt DW130V Mud Mixer",
          ]),
          costLow: 180,
          costHigh: 350,
          priority: "essential",
          phase: 1,
          supplierName: "Home Depot Pro",
          supplierUrl: "https://homedepot.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 2,
        },
      ],
    },
    {
      name: "GFRC Spray Equipment",
      slug: "gfrc-spray",
      phase: 1,
      phaseLabel: "Phase 1 — GFRC Fabrication",
      sortOrder: 2,
      items: [
        {
          name: "Face Coat Sprayer — Precision",
          description:
            "Fine mist sprayer for applying the face coat layer. Produces a smooth, even surface finish.",
          why: "The face coat is what the customer sees. A precision sprayer produces the fine, even layer needed for a flawless surface with minimal pinholes.",
          options: JSON.stringify([
            "RimCraft Titan Sprayer (premium)",
            "Sharpshooter 2.1 Hopper Gun by Marshalltown (budget)",
          ]),
          costLow: 85,
          costHigh: 650,
          priority: "essential",
          phase: 1,
          supplierName: "Expressions Ltd",
          supplierUrl: "https://expressions-ltd.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 1,
        },
        {
          name: "Backer Coat Sprayer",
          description:
            "Hopper-style sprayer for applying the backing coat with AR glass fiber for structural strength.",
          why: "The backer coat carries the AR glass fiber that gives GFRC its structural strength. A dedicated hopper sprayer handles the heavier fiber-laden mix that would clog a standard sprayer.",
          options: JSON.stringify([
            "RimCraft BakHopper",
            "Benron 30-300-E GFRC Hopper Sprayer",
          ]),
          costLow: 350,
          costHigh: 1200,
          priority: "essential",
          phase: 1,
          supplierName: "RimCraft",
          supplierUrl: "https://rimcraft.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 2,
        },
        {
          name: "Industrial Air Compressor",
          description:
            "Two-stage compressor with minimum 20 CFM at 90 PSI and 60-gallon tank. Powers all spray equipment.",
          why: "All spray applications require consistent, high-volume air supply. Undersized compressors cause pressure drops mid-spray that ruin surface quality. Two-stage with a large tank is mandatory.",
          options: JSON.stringify([
            "Ingersoll Rand 2340L5-V 60 gal",
            "Quincy QT-54 60 gal",
            "DeWalt DXCMV5048055 80 gal",
          ]),
          costLow: 800,
          costHigh: 1800,
          priority: "essential",
          phase: 1,
          supplierName: "Grainger",
          supplierUrl: "https://grainger.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 3,
        },
        {
          name: "Compaction Rollers",
          description:
            "Aluminum rollers in 1–4 inch diameters for consolidating the backer coat and eliminating air voids.",
          why: "Rolling the backer coat after spraying consolidates the fibers and eliminates air pockets that would create weak spots. A set covering multiple diameters handles corners and flat fields.",
          options: JSON.stringify([
            "Concrete Countertop Supply roller set",
            "Buddy Rhodes roller set",
          ]),
          costLow: 80,
          costHigh: 200,
          priority: "essential",
          phase: 1,
          supplierName: "Concrete Countertop Supply",
          supplierUrl: "https://concretecountertopsupply.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 4,
        },
      ],
    },
    {
      name: "Mold Making Equipment",
      slug: "mold-making",
      phase: 1,
      phaseLabel: "Phase 1 — GFRC Fabrication",
      sortOrder: 3,
      items: [
        {
          name: "Mold Table — Steel Fabrication",
          description:
            "Heavy steel table minimum 5 ft x 12 ft with a 3/4-inch steel top that is verified perfectly flat.",
          why: "Every mold is built on this table, so flatness is non-negotiable. A warped table produces warped panels. Steel construction withstands the weight of concrete molds and repeated use without deflection.",
          options: JSON.stringify([
            "Custom fabrication (local steel fab)",
            "Stronghand Tools BuildPro table (modular)",
          ]),
          costLow: 800,
          costHigh: 2500,
          priority: "essential",
          phase: 1,
          supplierName: "Local Steel Fabricator",
          supplierUrl: null,
          supplierNotes: null,
          quantity: 1,
          sortOrder: 1,
        },
        {
          name: "Melamine Board — Mold Material",
          description:
            "3/4-inch melamine-coated particle board used as the primary mold surface material.",
          why: "Melamine provides a smooth, non-porous release surface that gives GFRC its finished face texture. It cuts cleanly, holds fasteners, and the coating releases cured concrete without adhesion.",
          options: JSON.stringify([
            "Home Depot 3/4 inch melamine",
            "Local lumber yard bulk",
          ]),
          costLow: 200,
          costHigh: 400,
          priority: "essential",
          phase: 1,
          supplierName: "Home Depot",
          supplierUrl: "https://homedepot.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 2,
        },
        {
          name: "Mold Release and Sealants",
          description:
            "PU foam backer rod, mold release wax, and NP1 polyurethane caulk for sealing mold joints.",
          why: "Proper mold release prevents panels from bonding to the mold, and NP1 caulk seals all joints to prevent slurry bleed. Without these, molds tear panels apart during demold.",
          options: JSON.stringify([
            "Buddy Rhodes Mold Release Wax",
            "Rain-X (DIY)",
            "Sonneborn NP1",
          ]),
          costLow: 200,
          costHigh: 400,
          priority: "essential",
          phase: 1,
          supplierName: "Buddy Rhodes",
          supplierUrl: "https://buddyrhodes.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 3,
        },
        {
          name: "Vibration Tools",
          description:
            "Rubber mallet set, orbital sander used as a vibrator against mold sides, and optional pencil vibrator for consolidation.",
          why: "Vibration consolidates the mix against the mold face to eliminate surface voids and pinholes. Even an orbital sander pressed against the mold dramatically improves surface quality on small pours.",
          options: JSON.stringify([
            "Standard rubber mallet",
            "Old orbital sander pressed against mold",
            "Oztec pencil vibrator (premium)",
          ]),
          costLow: 80,
          costHigh: 250,
          priority: "recommended",
          phase: 1,
          supplierName: "Home Depot",
          supplierUrl: "https://homedepot.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 4,
        },
      ],
    },
    {
      name: "Grinding and Polishing",
      slug: "grinding-polishing",
      phase: 2,
      phaseLabel: "Phase 2 — Surface Finishing",
      sortOrder: 4,
      items: [
        {
          name: "Angle Grinder — Variable Speed (x2)",
          description:
            "4.5–5 inch variable speed angle grinder. Purchase two units — one for coarse grinding, one for polishing pads.",
          why: "Variable speed is critical: coarse diamond wheels need lower RPM to cut cleanly, while polishing pads run faster for surface sheen. Owning two avoids constant wheel swaps and extends both tool life.",
          options: JSON.stringify([
            "Makita GA5020C 5 inch",
            "DeWalt DWE402 4.5 inch",
            "Metabo WP 125-15",
          ]),
          costLow: 240,
          costHigh: 560,
          priority: "essential",
          phase: 2,
          supplierName: "Grainger",
          supplierUrl: "https://grainger.com",
          supplierNotes: null,
          quantity: 2,
          sortOrder: 1,
        },
        {
          name: "Diamond Cup Wheels — Grinding Set",
          description:
            "Diamond cup wheels in grits 50, 100, and 200 for progressive surface grinding.",
          why: "Each grit removes the scratch pattern from the previous step. Skipping grits leaves deep scratches that polishing pads cannot remove. A full set from 50 to 200 is required for predictable results.",
          options: JSON.stringify([
            "Alpha Professional Tools",
            "Husqvarna Tacti-Cut",
            "Stadea Series Supreme",
          ]),
          costLow: 200,
          costHigh: 600,
          priority: "essential",
          phase: 2,
          supplierName: "Alpha Professional Tools",
          supplierUrl: "https://alpha-tools.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 2,
        },
        {
          name: "Diamond Polishing Pad Set",
          description:
            "Velcro-backed resin diamond pads in grits 400, 800, 1500, and 3000 for wet or dry polishing.",
          why: "After grinding, these pads progressively refine the surface to the desired sheen level. Wet pads reduce heat and silica dust while producing a cleaner cut through each grit.",
          options: JSON.stringify([
            "Stadea Series Supreme wet/dry",
            "Alpha Professional Tools resin pads",
          ]),
          costLow: 150,
          costHigh: 400,
          priority: "essential",
          phase: 2,
          supplierName: "Stadea",
          supplierUrl: "https://stadea.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 3,
        },
        {
          name: "Concrete Densifier and Sealer",
          description:
            "Lithium silicate densifier applied before sealing, followed by a penetrating UV-resistant topcoat sealer.",
          why: "Densifier reacts with calcium hydroxide in the concrete to harden the surface and reduce porosity. Without it, the sealer sits on a weak surface layer that will peel. Proper sealing is what makes the product customer-ready.",
          options: JSON.stringify([
            "Consolideck LS",
            "Consolideck LSGuard",
            "Custom UV-resistant topcoat",
          ]),
          costLow: 200,
          costHigh: 500,
          priority: "essential",
          phase: 2,
          supplierName: "Prosoco",
          supplierUrl: "https://prosoco.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 4,
        },
      ],
    },
    {
      name: "Dust Collection",
      slug: "dust-collection",
      phase: 2,
      phaseLabel: "Phase 2 — Surface Finishing",
      sortOrder: 5,
      items: [
        {
          name: "Industrial HEPA Vacuum",
          description:
            "HEPA-filtered wet/dry vacuum with minimum 150 CFM suction for use during all concrete grinding and cutting operations.",
          why: "Crystalline silica dust from concrete grinding causes silicosis, an irreversible and fatal lung disease. OSHA requires engineering controls including HEPA vacuum attachment during all grinding. An N95 mask alone is not sufficient compliance.",
          options: JSON.stringify([
            "Festool CT professional",
            "Pullman-Ermator S26",
            "Makita XCV11Z",
          ]),
          costLow: 600,
          costHigh: 1800,
          priority: "essential",
          phase: 2,
          supplierName: "Festool",
          supplierUrl: "https://festool.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 1,
        },
        {
          name: "Dust Shrouds for Grinders",
          description:
            "Dust shroud attachment connecting each angle grinder to the HEPA vacuum. One unit per grinder.",
          why: "Without a shroud, even a HEPA vacuum cannot capture silica dust at the grinding surface. The shroud creates a sealed capture zone directly at the source, which is the only effective method for silica control during grinding.",
          options: JSON.stringify([
            "Malco Products dust shroud",
            "Makita 196846-1",
            "Dustless Technologies shroud",
          ]),
          costLow: 160,
          costHigh: 360,
          priority: "essential",
          phase: 2,
          supplierName: "Grainger",
          supplierUrl: "https://grainger.com",
          supplierNotes: null,
          quantity: 2,
          sortOrder: 2,
        },
      ],
    },
    {
      name: "UV Print Equipment",
      slug: "uv-print",
      phase: 3,
      phaseLabel: "Phase 3 — UV Print",
      sortOrder: 6,
      items: [
        {
          name: "UV Flatbed Printer — Epson SureColor V7000",
          description:
            "4x8 print bed UV flatbed printer with 10-color UV ink system and 720x1440 dpi resolution.",
          why: "UV flatbed printing directly onto GFRC panels is the core value-add of the product line. However, the capital cost is significant and outsourcing is viable at low volume — buy only after volume justifies the investment.",
          options: JSON.stringify([
            "Epson SureColor V7000 (entry level)",
            "Roland EU-1000MF (mid range)",
            "OUTSOURCE FIRST",
          ]),
          costLow: 0,
          costHigh: 45000,
          priority: "optional",
          phase: 3,
          supplierName: "Epson",
          supplierUrl: "https://epson.com",
          supplierNotes:
            "RECOMMENDATION: Outsource printing for first 3 installations. Buy printer after volume justifies investment. Outsource cost ~$8-15 per sq ft.",
          quantity: 1,
          sortOrder: 1,
        },
        {
          name: "RIP Software",
          description:
            "Raster Image Processing software for professional color management and print queue control.",
          why: "RIP software provides the color accuracy and print control that standard print drivers cannot achieve. It handles ICC profiles, ink limiting, and queue management — all critical for consistent output quality.",
          options: JSON.stringify([
            "Onyx RIP",
            "Caldera RIP",
            "Epson Edge Print (included with V7000)",
          ]),
          costLow: 0,
          costHigh: 3500,
          priority: "optional",
          phase: 3,
          supplierName: "Onyx Graphics",
          supplierUrl: "https://onyxgfx.com",
          supplierNotes:
            "Only needed if purchasing UV printer. Epson V7000 includes basic RIP software.",
          quantity: 1,
          sortOrder: 2,
        },
        {
          name: "Print Workstation Computer",
          description:
            "High-performance workstation with 32 GB RAM minimum and 2 TB SSD for handling large print files.",
          why: "UV print files for large-format panels are enormous — often 2–10 GB per job. Insufficient RAM causes the RIP software to swap to disk, dramatically slowing print preparation and creating workflow bottlenecks.",
          options: JSON.stringify([
            "Apple Mac Studio M3 Pro 36GB",
            "PC AMD Ryzen 9 or Intel i9 32GB",
          ]),
          costLow: 2500,
          costHigh: 4500,
          priority: "optional",
          phase: 3,
          supplierName: "Apple",
          supplierUrl: "https://apple.com",
          supplierNotes:
            "Only needed if purchasing UV printer. Can use existing computer initially.",
          quantity: 1,
          sortOrder: 3,
        },
      ],
    },
    {
      name: "Metalwork Equipment",
      slug: "metalwork",
      phase: 4,
      phaseLabel: "Phase 4 — Steel Fabrication",
      sortOrder: 7,
      items: [
        {
          name: "MIG Welder — 220V",
          description:
            "220V MIG welder with minimum 180-amp output for fabricating U-brackets, insert blocks, and structural steel components.",
          why: "GFRC panels require embedded steel inserts and hanging hardware that must be fabricated in-house to match each project's specific geometry. A 180-amp 220V MIG welder handles the steel gauges used in bracket fabrication.",
          options: JSON.stringify([
            "Lincoln Electric 210MP",
            "Miller Millermatic 211",
            "Hobart Handler 210MVP",
          ]),
          costLow: 800,
          costHigh: 1400,
          priority: "recommended",
          phase: 4,
          supplierName: "Lincoln Electric",
          supplierUrl: "https://lincolnelectric.com",
          supplierNotes:
            "Alternative: outsource steel fab to local shop for first 2-3 projects.",
          quantity: 1,
          sortOrder: 1,
        },
        {
          name: "Angle Grinder — Metal Dedicated",
          description:
            "4.5-inch angle grinder dedicated exclusively to metalwork. Never cross-contaminate with concrete grinding equipment.",
          why: "Metal contamination from concrete-used grinding wheels causes rust staining in GFRC. A dedicated metal grinder with its own discs and wire cups prevents cross-contamination and protects finished concrete surfaces.",
          options: JSON.stringify(["DeWalt DWE402", "Makita 9557PB"]),
          costLow: 120,
          costHigh: 200,
          priority: "recommended",
          phase: 4,
          supplierName: "Home Depot",
          supplierUrl: "https://homedepot.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 2,
        },
        {
          name: "Metal Cutting Saw",
          description:
            "Horizontal band saw or metal chop saw for cutting steel stock to length.",
          why: "Accurate, repeatable steel cuts are required for bracket fabrication. An angle grinder with a cutoff wheel is slow and imprecise for production work. A dedicated cutting saw reduces fabrication time and improves dimensional accuracy.",
          options: JSON.stringify([
            "WEN 3975T 4.5 inch",
            "JET HVBS-56M",
            "Evolution RAGE2",
          ]),
          costLow: 400,
          costHigh: 900,
          priority: "recommended",
          phase: 4,
          supplierName: "JET Tools",
          supplierUrl: "https://jettools.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 3,
        },
        {
          name: "Bench Drill Press",
          description:
            "12-inch swing minimum variable-speed bench drill press for drilling holes in steel brackets and inserts.",
          why: "Freehand drilling in steel produces inaccurate hole placement and dangerous bit grabbing. A drill press with a vise produces consistent, perpendicular holes in steel and allows safe use of larger-diameter bits.",
          options: JSON.stringify([
            "JET JDP-20MF 20 inch",
            "WEN 4214 12 inch bench",
            "Powermatic 2800B",
          ]),
          costLow: 350,
          costHigh: 700,
          priority: "recommended",
          phase: 4,
          supplierName: "JET Tools",
          supplierUrl: "https://jettools.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 4,
        },
        {
          name: "Bench Vise",
          description:
            "Heavy-duty bench vise with 6-inch minimum jaw width for holding steel during cutting, filing, and assembly.",
          why: "A solid bench vise is the most-used hand tool in any metal fabrication workflow. It holds work securely for filing, tapping threads, bending, and fitting — tasks that cannot be safely done freehand.",
          options: JSON.stringify([
            "Wilton 63185 6.5 inch",
            "Yost FSV-6 6 inch swivel",
          ]),
          costLow: 200,
          costHigh: 450,
          priority: "recommended",
          phase: 4,
          supplierName: "Wilton",
          supplierUrl: "https://wiltontools.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 5,
        },
        {
          name: "Welding Table",
          description:
            "Flat steel welding table with fixture holes for clamping and positioning steel components during fabrication.",
          why: "A proper welding table with fixture slots allows brackets and frames to be clamped in exact position before welding, preventing distortion and ensuring repeatable geometry across production runs.",
          options: JSON.stringify([
            "Stronghand Tools FixturePoint",
            "Custom welded",
            "Fireball Tool table",
          ]),
          costLow: 600,
          costHigh: 1500,
          priority: "recommended",
          phase: 4,
          supplierName: "Stronghand Tools",
          supplierUrl: "https://stronghandtools.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 6,
        },
        {
          name: "Auto-Darkening Welding Helmet",
          description:
            "Auto-darkening welding helmet with arc flash protection for all MIG welding operations.",
          why: "Arc flash causes permanent eye damage in a fraction of a second. Auto-darkening allows the welder to position the torch before the arc strikes without flipping the helmet, which reduces neck fatigue and improves weld quality.",
          options: JSON.stringify([
            "Lincoln Electric Viking 3350",
            "Miller Digital Elite",
            "Lincoln K3034-4",
          ]),
          costLow: 80,
          costHigh: 200,
          priority: "essential",
          phase: 4,
          supplierName: "Lincoln Electric",
          supplierUrl: "https://lincolnelectric.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 7,
        },
      ],
    },
    {
      name: "Material Handling",
      slug: "material-handling",
      phase: 5,
      phaseLabel: "Phase 5 — General Studio",
      sortOrder: 8,
      items: [
        {
          name: "Manual Pallet Jack",
          description:
            "5,500 lb capacity manual pallet jack for moving material pallets and heavy molds within the studio.",
          why: "GFRC panel pallets and raw material bags arrive on standard pallets and cannot be moved safely by hand. A pallet jack is required for basic receiving and shop logistics from day one.",
          options: JSON.stringify([
            "Vestil PJSF-2748-27",
            "Uline H-1046",
          ]),
          costLow: 300,
          costHigh: 800,
          priority: "essential",
          phase: 5,
          supplierName: "Uline",
          supplierUrl: "https://uline.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 1,
        },
        {
          name: "A-Frame Panel Cart",
          description:
            "A-frame cart for transporting finished GFRC slats upright to prevent flexure stress and surface damage.",
          why: "GFRC slats stored or transported flat are vulnerable to breakage from their own weight. An A-frame cart keeps them vertical and supported at the edges, which is the only safe transport orientation for thin panels.",
          options: JSON.stringify([
            "Vestil A-frame panel cart",
            "Custom welded A-frame",
          ]),
          costLow: 400,
          costHigh: 800,
          priority: "essential",
          phase: 5,
          supplierName: "Vestil",
          supplierUrl: "https://vestilmfg.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 2,
        },
        {
          name: "Freestanding Gantry Crane",
          description:
            "1-ton minimum adjustable-height freestanding gantry crane for lifting and positioning molds and finished panels.",
          why: "Large GFRC molds and finished panel assemblies exceed safe manual lift weight. A gantry crane allows a two-person crew to safely lift, rotate, and position heavy work without forklift access or structural overhead hooks.",
          options: JSON.stringify([
            "Jet GCL-1000",
            "Vestil GAN-4-10",
            "Spanco 1AB-1-10",
          ]),
          costLow: 800,
          costHigh: 2000,
          priority: "recommended",
          phase: 5,
          supplierName: "JET Tools",
          supplierUrl: "https://jettools.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 3,
        },
        {
          name: "Vertical Panel Storage Rack",
          description:
            "Vertical storage rack holding up to 32 GFRC slats upright with padded dividers.",
          why: "Finished slats awaiting installation must be stored vertically to prevent sagging and cracking. A dedicated rack with dividers prevents panels from contacting each other, protecting finished UV-printed surfaces.",
          options: JSON.stringify([
            "Custom welded",
            "Edsal Panel Storage Rack",
          ]),
          costLow: 600,
          costHigh: 1500,
          priority: "recommended",
          phase: 5,
          supplierName: "Local Steel Fabricator",
          supplierUrl: null,
          supplierNotes: null,
          quantity: 1,
          sortOrder: 4,
        },
      ],
    },
    {
      name: "Safety Equipment",
      slug: "safety",
      phase: 5,
      phaseLabel: "Phase 5 — General Studio",
      sortOrder: 9,
      items: [
        {
          name: "P100 Half-Face Respirators",
          description:
            "3M 6500 series half-face respirators with P100 cartridges. Minimum purchase of 3 units.",
          why: "P100 filtration is mandatory for silica dust — not N95. N95 respirators do not meet OSHA silica standards for grinding operations. Three units ensure all personnel working in the grinding area are protected simultaneously.",
          options: JSON.stringify([
            "3M 6502QL Quick Latch",
            "3M 6503QL large",
            "3M 2091 P100 cartridges",
          ]),
          costLow: 105,
          costHigh: 165,
          priority: "essential",
          phase: 5,
          supplierName: "Grainger",
          supplierUrl: "https://grainger.com",
          supplierNotes: null,
          quantity: 3,
          sortOrder: 1,
        },
        {
          name: "Safety Glasses and Face Shields",
          description:
            "ANSI Z87.1-rated safety glasses set of 6 units, plus 2 full face shields for grinding and chipping operations.",
          why: "Flying concrete chips and metal sparks cause eye injuries without warning. ANSI Z87.1 glasses protect against impact; face shields add coverage for grinding operations where chips travel at high velocity.",
          options: JSON.stringify([
            "3M SecureFit ANSI Z87.1",
            "Uvex Bionic Face Shield",
          ]),
          costLow: 80,
          costHigh: 200,
          priority: "essential",
          phase: 5,
          supplierName: "Grainger",
          supplierUrl: "https://grainger.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 2,
        },
        {
          name: "Hearing Protection",
          description:
            "NRR 25+ earmuffs for use during grinding, compressor operation, and pneumatic tool use. Purchase 4 units.",
          why: "Angle grinders and air compressors exceed 90 dB, the OSHA threshold for mandatory hearing protection. Earmuffs are faster to don than earplugs, making compliance more consistent in a fast-paced shop environment.",
          options: JSON.stringify([
            "3M PELTOR Optime 105 NRR 30",
            "Howard Leight Sync NRR 25",
          ]),
          costLow: 30,
          costHigh: 80,
          priority: "essential",
          phase: 5,
          supplierName: "Grainger",
          supplierUrl: "https://grainger.com",
          supplierNotes: null,
          quantity: 4,
          sortOrder: 3,
        },
        {
          name: "Nitrile Gloves — Bulk Case",
          description:
            "Heavy-duty nitrile gloves in bulk case quantity for protection against wet cement and chemical sealers.",
          why: "Wet cement is caustic and causes chemical burns with prolonged skin contact. Nitrile resists cement alkalinity and the solvents in concrete sealers and release agents better than latex or vinyl alternatives.",
          options: JSON.stringify([
            "Kimberly-Clark KleenGuard G40",
            "Ansell Edge 82-134",
          ]),
          costLow: 60,
          costHigh: 120,
          priority: "essential",
          phase: 5,
          supplierName: "Grainger",
          supplierUrl: "https://grainger.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 4,
        },
        {
          name: "Fire Extinguishers",
          description:
            "ABC-rated 10 lb minimum fire extinguishers. Purchase two units for placement at shop entry and welding area.",
          why: "Welding and grinding both create ignition sources in an environment with combustible materials. OSHA and most commercial building codes require minimum fire extinguisher coverage per square footage, and the welding area demands a dedicated unit.",
          options: JSON.stringify([
            "Kidde Pro 210 4lb",
            "Kidde Pro 340 10lb",
          ]),
          costLow: 80,
          costHigh: 160,
          priority: "essential",
          phase: 5,
          supplierName: "Home Depot",
          supplierUrl: "https://homedepot.com",
          supplierNotes: null,
          quantity: 2,
          sortOrder: 5,
        },
        {
          name: "First Aid Kit — Industrial",
          description:
            "ANSI Class B compliant industrial first aid kit for a multi-person shop environment.",
          why: "An ANSI Class B kit is the minimum compliant first aid supply level for manufacturing environments. It covers lacerations, burns, and eye injuries — the most common incidents in concrete and metalwork shops.",
          options: JSON.stringify([
            "First Aid Only ANSI Class B 150 person",
            "Genuine First Aid ANSI B Cabinet",
          ]),
          costLow: 80,
          costHigh: 150,
          priority: "essential",
          phase: 5,
          supplierName: "Grainger",
          supplierUrl: "https://grainger.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 6,
        },
      ],
    },
    {
      name: "Shop Infrastructure",
      slug: "infrastructure",
      phase: 6,
      phaseLabel: "Phase 6 — Studio Infrastructure",
      sortOrder: 10,
      items: [
        {
          name: "Electrical Panel Upgrade",
          description:
            "100-amp minimum sub-panel installation by a licensed electrician. Upgrade to 200-amp if UV printer is purchased.",
          why: "The combined draw of a two-stage air compressor, MIG welder, forced-action mixer, and dust collector exceeds standard shop panel capacity. Dedicated circuits prevent nuisance tripping and are required by code for equipment over 20 amps.",
          options: JSON.stringify([
            "Square D QO 100 amp",
            "Siemens MC0816B1200SC 200 amp",
          ]),
          costLow: 3000,
          costHigh: 8000,
          priority: "essential",
          phase: 6,
          supplierName: "Local Licensed Electrician",
          supplierUrl: null,
          supplierNotes:
            "Circuits: Air compressor 30A, Welder 50A, Mixer 20A, UV Printer 30A, Dust collector 20A, Multiple 20A general.",
          quantity: 1,
          sortOrder: 1,
        },
        {
          name: "Industrial Exhaust Fan System",
          description:
            "Wall or ceiling-mounted industrial exhaust fan with minimum 4,000 CFM for whole-shop ventilation.",
          why: "Concrete dust, solvent fumes from sealers, and welding smoke accumulate rapidly in an enclosed shop. Adequate air changes per hour via a high-CFM exhaust fan is required for both OSHA air quality compliance and worker health.",
          options: JSON.stringify([
            "Canarm direct drive 4000 CFM",
            "Global Industrial 5000 CFM",
            "TPI Corp commercial",
          ]),
          costLow: 400,
          costHigh: 1200,
          priority: "essential",
          phase: 6,
          supplierName: "Grainger",
          supplierUrl: "https://grainger.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 2,
        },
        {
          name: "Welding Fume Extractor",
          description:
            "Portable source-capture fume extractor positioned at the welding point to remove welding fumes before they enter the breathing zone.",
          why: "Whole-shop ventilation alone is insufficient for welding fumes. OSHA requires source capture for welding because manganese and hexavalent chromium fumes cause irreversible neurological and respiratory damage with cumulative exposure.",
          options: JSON.stringify([
            "Plymovent MobileGo",
            "Lincoln Electric K3813-1",
            "Donaldson Torit",
          ]),
          costLow: 600,
          costHigh: 1500,
          priority: "essential",
          phase: 6,
          supplierName: "Lincoln Electric",
          supplierUrl: "https://lincolnelectric.com",
          supplierNotes: null,
          quantity: 1,
          sortOrder: 3,
        },
        {
          name: "Utility Sink and Wash Station",
          description:
            "Heavy-duty utility sink with a sediment trap installed. Concrete washout must never enter the municipal sewer without a permitted trap.",
          why: "Concrete washwater is highly alkaline and contains suspended solids that solidify in drain pipes and violate wastewater discharge standards. A sediment trap captures concrete solids before washwater enters the sewer system.",
          options: JSON.stringify([
            "Mustee 25 heavy duty",
            "Concrete washout container",
            "Custom wash station",
          ]),
          costLow: 200,
          costHigh: 600,
          priority: "essential",
          phase: 6,
          supplierName: "Home Depot",
          supplierUrl: "https://homedepot.com",
          supplierNotes:
            "Install with sediment trap. Do not connect to municipal sewer without concrete washout permit.",
          quantity: 1,
          sortOrder: 4,
        },
      ],
    },
  ];

  for (const cat of categories) {
    const category = await prisma.equipmentCategory.create({
      data: {
        name: cat.name,
        slug: cat.slug,
        phase: cat.phase,
        phaseLabel: cat.phaseLabel,
        sortOrder: cat.sortOrder,
      },
    });

    for (const item of cat.items) {
      await prisma.equipmentItem.create({
        data: {
          categoryId: category.id,
          name: item.name,
          description: item.description,
          why: item.why,
          options: item.options,
          costLow: item.costLow,
          costHigh: item.costHigh,
          priority: item.priority,
          phase: item.phase,
          supplierName: item.supplierName ?? null,
          supplierUrl: item.supplierUrl ?? null,
          supplierNotes: item.supplierNotes ?? null,
          status: "needed",
          quantity: item.quantity ?? 1,
          sortOrder: item.sortOrder,
        },
      });
    }
  }

  // Create initial budget record
  await prisma.equipmentBudget.create({
    data: {
      label: "Studio Build Budget",
      allocatedAmount: 25000,
      notes: "Initial allocation for Phase 1-2 equipment",
    },
  });

  console.log("Equipment data seeded successfully.");
}

if (require.main === module) {
  seedEquipment()
    .then(() => process.exit(0))
    .catch((e) => {
      console.error(e);
      process.exit(1);
    });
}
