import Link from "next/link";
import { TrendingUp } from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { listIntelReports } from "@/lib/services/intel-report-service";
import { requireSession } from "@/lib/auth/session";

export const dynamic = "force-dynamic";

function fmtDate(d: Date): string {
  return new Date(d).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" });
}

export default async function IntelReportsPage() {
  await requireSession();
  const reports = await listIntelReports();

  return (
    <div className="space-y-6">
      <header>
        <h1 className="flex items-center gap-2 text-2xl font-bold tracking-tight sm:text-3xl">
          <TrendingUp className="size-6" />
          Market Intelligence Reports
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Weekly architectural concrete market briefings generated by Jacob every Monday at 8 AM Central.
        </p>
      </header>

      {reports.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center text-sm text-muted-foreground">
            No reports yet. The first report will be generated next Monday morning.
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {reports.map((r) => (
            <Link key={r.id} href={`/intel-reports/${r.id}`}>
              <Card className="transition hover:border-primary/50 hover:shadow-sm">
                <CardHeader>
                  <CardTitle className="text-base">Week of {fmtDate(r.weekOf)}</CardTitle>
                  <p className="mt-1 text-xs text-muted-foreground">
                    Generated {fmtDate(r.generatedAt)}
                    {r.estimatedCostUsd ? ` · $${Number(r.estimatedCostUsd).toFixed(2)} cost` : ""}
                    {r.model ? ` · ${r.model}` : ""}
                  </p>
                </CardHeader>
                <CardContent>
                  <p className="text-sm leading-relaxed line-clamp-3 text-foreground/85">
                    {r.executiveSummary.replace(/^[-•*]\s*/gm, "").slice(0, 400)}
                  </p>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
