-- AlterTable
ALTER TABLE "skus" DROP COLUMN "dimensionsJson",
ADD COLUMN     "bottomThickness" DECIMAL(8,2),
ADD COLUMN     "cornerRadius" DECIMAL(8,2),
ADD COLUMN     "crossRibCount" INTEGER,
ADD COLUMN     "domeRiseMax" DECIMAL(8,2),
ADD COLUMN     "domeRiseMin" DECIMAL(8,2),
ADD COLUMN     "draftAngle" DECIMAL(8,2),
ADD COLUMN     "drainDiameter" DECIMAL(8,2),
ADD COLUMN     "fiberPercent" DECIMAL(5,4),
ADD COLUMN     "hollowCoreDepth" DECIMAL(8,2),
ADD COLUMN     "innerDepth" DECIMAL(8,2),
ADD COLUMN     "innerLength" DECIMAL(8,2),
ADD COLUMN     "innerWidth" DECIMAL(8,2),
ADD COLUMN     "longRibCount" INTEGER,
ADD COLUMN     "outerHeight" DECIMAL(8,2),
ADD COLUMN     "outerLength" DECIMAL(8,2),
ADD COLUMN     "outerWidth" DECIMAL(8,2),
ADD COLUMN     "reinforcementDiameter" DECIMAL(8,2),
ADD COLUMN     "reinforcementThickness" DECIMAL(8,2),
ADD COLUMN     "ribHeight" DECIMAL(8,2),
ADD COLUMN     "ribWidth" DECIMAL(8,2),
ADD COLUMN     "topLipThickness" DECIMAL(8,2),
ADD COLUMN     "wallThickness" DECIMAL(8,2);
